const QUOTES = [
    //NOTE: following quotes are generated by AI.
    "Don't give up! High-quality work takes time. 🚀",
    "Keep going! You're almost there! 🚀",
    "Persistence is the path to mastery. ✨",
    "Even the best were once where you are. 🌟",
    "Believe in yourself, you've got this! 🔍",
    "One step at a time. You're doing great. ✅",
    "Every challenge is an opportunity to grow. ✨",
    "You are capable of amazing things. Keep showing up!📈",
    "Don't worry about the speed, worry about the journey. ⏱️",
    "Consistency beats intensity. Every day counts. 📅",
    "You are more than your LeetCode rank. ⭐",
    "You are smarter than this while loop. 🔄",
    "If it was easy, everyone would be a Senior Engineer. 👑",
    "The most efficient solution isn't always the first one. 💡",
    "Try sketching the logic on paper first. 📝",
    "Visualize the data structure in your mind. 🧊",
    "The compiler is your partner, not your critic. 🤝",
    "Every 'Run Code' is a step toward mastery. ⚡",
    "Your future self will thank you for not quitting today. 🌅",
    "Coding is 90% thinking and 10% typing. 💭",
    "Refactoring is where the magic happens. ✨",
    "The best way to learn is to struggle a little. 🧗",
    "You're building mental muscles with every line. 🏋️",
    "Stay calm and keep coding. 🧘",
    "Take a deep breath. A fresh perspective is just a break away. ☕",
    "Step away from the screen for a moment. Your brain will thank you. 🚶‍♂️",
    "Hydrate and stretch. Your code will still be here when you get back. 💧",
    "Sometimes the best debugging tool is a short walk. 🌳",
    "Rest is productive. Give your mind a chance to reset. 🛌",
    "The logic is sound; keep searching for the implementation. 🔭",
    "Optimization is a journey, not a destination. 🚀",
    "Believe in your logic. It's gotten you this far. 🎖️",
    "Debug high, code low. You're mastering the flow. 🌊",
    "The best way to predict the future is to code it. 💻",
    "Small commits, big impact. Keep moving forward. 🔨",
    "Your logic is valid. Your effort is noticed. 🌈",
    "Every bug fixed is a lesson learned. 🐛✨",
    "Complexity is the enemy; persistence is the cure. 🛡️",
];


function handleInteraction() {
    const now = Date.now();
    const fiveMinutesAgo = now - (5 * 60 * 1000);
    const coolDownTime = 10 * 60 * 1000; // 10 minutes

    chrome.storage.local.get(['clickStamp', 'lastShown'], (result) => {
        let clicks = result.clickStamp || [];
        let lastShown = result.lastShown || 0;
        clicks.push(now);
        clicks = clicks.filter(time => time > fiveMinutesAgo);
        const isStuck = clicks.length >= 3;
        const isCooledDown = now - lastShown > coolDownTime;

        if (isStuck && isCooledDown) {
            showMotivation('stuck');
            chrome.storage.local.set({ lastShown: now });
        }

        chrome.storage.local.set({ clickStamp: clicks })
    })

}

function setupButtons() {
    const selectors = [
        '[data-e2e-locator="console-run-button"]',
        '[data-e2e-locator="console-submit-button"]'
    ]

    selectors.forEach(selector => {
        const btn = document.querySelector(selector);
        if (btn && !btn.dataset.listenerAttached) {
            console.log("Target acquired!");
            btn.dataset.listenerAttached = "true";
            btn.addEventListener('click', () => {
                handleInteraction();
            });
        }
    })
}


function showMotivation(reason = 'stuck') {
    if (document.getElementById('motivation-host-box')) {
        return;
    }

    let title = "Motivation Strike";
    let icon = "✨";

    if (reason === 'inactive') {
        title = "Inactivity Alert";
        icon = "⚡";
    }

    const host = document.createElement('div');
    host.id = 'motivation-host-box';

    host.style.position = 'fixed';
    host.style.bottom = '24px';
    host.style.right = '24px';
    host.style.zIndex = '9999';
    host.style.pointerEvents = 'none';

    const shadow = host.attachShadow({ mode: 'open' });
    shadow.innerHTML = `
        <style>
            @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;600&display=swap');

            :host {
                pointer-events: auto;
            }

            .banner {
                background: rgba(40, 40, 40, 0.85);
                backdrop-filter: blur(12px) saturate(180%);
                -webkit-backdrop-filter: blur(12px) saturate(180%);
                color: #eff1f6;
                padding: 20px;
                border-radius: 16px;
                border: 1px solid rgba(255, 255, 255, 0.1);
                font-family: 'Inter', -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
                box-shadow: 0 8px 32px 0 rgba(0, 0, 0, 0.37);
                width: 320px;
                transform: translateY(100px);
                opacity: 0;
                transition: all 0.5s cubic-bezier(0.19, 1, 0.22, 1);
                position: relative;
                overflow: hidden;
            }

            .banner.show {
                transform: translateY(0);
                opacity: 1;
            }

            .banner::before {
                content: '';
                position: absolute;
                top: 0;
                left: 0;
                width: 4px;
                height: 100%;
                background: linear-gradient(to bottom, #ffa116, #ff7b16);
            }

            .header {
                display: flex;
                align-items: center;
                gap: 10px;
                margin-bottom: 12px;
            }

            .icon {
                font-size: 20px;
                background: rgba(255, 161, 22, 0.1);
                padding: 6px;
                border-radius: 8px;
                display: flex;
                align-items: center;
                justify-content: center;
            }

            .title {
                font-weight: 600;
                font-size: 14px;
                color: #ffa116;
                text-transform: uppercase;
                letter-spacing: 0.5px;
            }

            .quote {
                font-size: 15px;
                line-height: 1.5;
                margin: 0 0 16px 0;
                color: #e0e0e0;
                opacity: 0;
                transform: translateY(5px);
                transition: all 0.4s ease 0.2s;
            }

            .banner.show .quote {
                opacity: 1;
                transform: translateY(0);
            }

            .footer {
                display: flex;
                justify-content: flex-end;
            }

            #close-btn {
                background: rgba(255, 255, 255, 0.05);
                color: #ffa116;
                border: 1px solid rgba(255, 161, 22, 0.3);
                padding: 8px 16px;
                border-radius: 8px;
                cursor: pointer;
                font-size: 13px;
                font-weight: 600;
                transition: all 0.2s ease;
                font-family: inherit;
            }

            #close-btn:hover {
                background: #ffa116;
                color: #1a1a1a;
                border-color: #ffa116;
                transform: translateY(-1px);
            }

            #close-btn:active {
                transform: translateY(0);
            }
        </style>
        <div class="banner" id="banner">
            <div class="header">
                <div class="icon">${icon}</div>
                <div class="title">${title}</div>
            </div>
            <p class="quote"></p>
            <div class="footer">
                <button id="close-btn">${reason === 'inactive' ? 'Back to Work' : 'Keep Crushing It'}</button>
            </div>
        </div>
    `
    const quote = QUOTES[Math.floor(Math.random() * QUOTES.length)];
    shadow.querySelector('.quote').textContent = quote;

    document.body.appendChild(host);

    // Trigger animation
    setTimeout(() => {
        shadow.getElementById('banner').classList.add('show');
    }, 10);

    shadow.getElementById('close-btn').onclick = () => {
        const banner = shadow.getElementById('banner');
        banner.classList.remove('show');
        setTimeout(() => host.remove(), 500);
    };
}



let inactivityTimer;

function resetInactivityTimer() {
    clearTimeout(inactivityTimer);
    inactivityTimer = setTimeout(() => {
        showMotivation('inactive')
    }, 10 * 60 * 1000);
}

document.addEventListener('keydown', resetInactivityTimer);
document.addEventListener('mousedown', resetInactivityTimer);


// 1. the observer
const observer = new MutationObserver(() => {
    setupButtons();

    //reset clickstamp on accepted
    let submissionResult = document.querySelector('[data-e2e-locator="submission-result"]');
    if (submissionResult && submissionResult.innerText.includes("Accepted")) {
        chrome.storage.local.set({ clickStamp: [] })
    }
});

// 2. Start observing
observer.observe(document.body, { childList: true, subtree: true });

// 3. RUNS ONCE IMMEDIATELY (imp for race conditions)
setupButtons();
